-- MySQL Script generated by MySQL Workbench
-- 04/22/15 10:16:46
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema hackday
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `hackday` ;

-- -----------------------------------------------------
-- Schema hackday
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `hackday` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `hackday` ;

-- -----------------------------------------------------
-- Table `hackday`.`data`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hackday`.`data` ;

CREATE TABLE IF NOT EXISTS `hackday`.`data` (
  `id` INT NOT NULL,
  `name` VARCHAR(75) NOT NULL,
  `data` LONGTEXT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hackday`.`cat0`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hackday`.`cat0` ;

CREATE TABLE IF NOT EXISTS `hackday`.`cat0` (
  `name` VARCHAR(25) NOT NULL,
  PRIMARY KEY (`name`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hackday`.`cat1`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hackday`.`cat1` ;

CREATE TABLE IF NOT EXISTS `hackday`.`cat1` (
  `cat0` VARCHAR(25) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`cat0`, `name`),
  CONSTRAINT `fk_cat1_cat0`
    FOREIGN KEY (`cat0`)
    REFERENCES `hackday`.`cat0` (`name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
